### ISSUE TITLE
没有 Github Page 的仓库也显示 GH Pages, 而且位置好丑。

### ISSUE THREAD

**Issue by xpol** [rubyerme/chrome-github-mate#14]
比如： https://github.com/lorentey/BTree

![image](https://cloud.githubusercontent.com/assets/20248/13494558/f333c110-e17f-11e5-9cd1-c89e39228cfa.png)

**Comment by camsong** [comment]
https://github.com/lorentey/BTree 是有 Github Pages 的，只是没有 index 页面
如 http://lorentey.github.io/BTree/api/Enums.html
